CREATE SEQUENCE IF NOT EXISTS revinfo_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE revinfo
(
    rev      INTEGER NOT NULL,
    revtstmp BIGINT,
    CONSTRAINT pk_revinfo PRIMARY KEY (rev)
);

CREATE TABLE public.organization
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         VARCHAR(50)                             NOT NULL,
    created_date       BIGINT                                  NOT NULL,
    last_modified_by   VARCHAR(50),
    last_modified_date BIGINT,
    name               VARCHAR(255),
    description        VARCHAR(255),
    phone              VARCHAR(255),
    address1           VARCHAR(255),
    address2           VARCHAR(255),
    city               VARCHAR(255),
    state              VARCHAR(255),
    zip                VARCHAR(255),
    country            VARCHAR(255),
    email              VARCHAR(255),
    contact_name       VARCHAR(255),
    website            VARCHAR(255),
    logo               VARCHAR(255),
    type               VARCHAR(255),
    status             VARCHAR(255),
    stripe_customer_id VARCHAR(255),
    shipping_address1  VARCHAR(255),
    shipping_address2  VARCHAR(255),
    shipping_city      VARCHAR(255),
    shipping_state     VARCHAR(255),
    shipping_zip       VARCHAR(255),
    shipping_country   VARCHAR(255),
    shipping_name      VARCHAR(255),
    shipping_phone     VARCHAR(255),
    CONSTRAINT pk_organization PRIMARY KEY (id)
);

CREATE TABLE public.organization_location
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    organization_id BIGINT,
    location_id     BIGINT,
    CONSTRAINT pk_organization_location PRIMARY KEY (id)
);

ALTER TABLE public.organization
    ADD CONSTRAINT organization_email_stripe_customer_id_key UNIQUE (email);

ALTER TABLE public.organization_location
    ADD CONSTRAINT organization_location_organization_id_location_id_key UNIQUE (organization_id, location_id);

ALTER TABLE public.organization
    ADD CONSTRAINT uc_organization_stripe_customer UNIQUE (stripe_customer_id);